### ISSUE TITLE
Can not add this package to Xcode 16

### ISSUE THREAD

**Issue by sebsto** [aws-geospatial/amazon-location-mobile-tracking-sdk-ios#7]
When trying to add this package to a new project using XCode 16, I receive the following error 

![image](https://github.com/user-attachments/assets/21fb303d-b95e-47d5-a04d-ae042240dde5)

**Comment by cgalvan** [comment]
We believe this has a similar root cause to https://github.com/aws-geospatial/amazon-location-mobile-auth-sdk-ios/issues/12.

Can you try specifying the package version as `Branch` instead of `Up to Next Major Version`?

**Comment by sebsto** [comment]
Using branch = main works.

**Comment by mbalfour-amzn** [comment]
We've released a new version of the tracking SDK (0.3.0) that should no longer cause the error reported above. Thanks for bringing this to our attention!

**Comment by sebsto** [comment]
I can confirm I can now add v 0.3.0 to an Xcode 16 project - thank you
